"use strict";Object.defineProperties(exports,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}});function F(e){const n=parseFloat(e);return typeof n=="number"&&!Number.isNaN(n)}function m(e,n,t){return Math.min(Math.max(e,n),t)}function d(e,n,t){return n+(t-n)*e}function I(e,n){return Math.round(e*10**n)/10**n}function M(e){const n=parseFloat(e);return e.toString().replace(n.toString(),"")}function D(e){return function(n,t,i){return n.map(r=>e(r,t,i))}}/*!
 * Spring solver inspired by Webkit Copyright © 2016 Apple Inc. All rights reserved. https://webkit.org/demos/spring/spring.js
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
*/const c=(e,[n=1,t=100,i=10,r=0]=[],a)=>{n=m(n,1e-4,1e3),t=m(t,1e-4,1e3),i=m(i,1e-4,1e3),r=m(r,1e-4,1e3);const u=Math.sqrt(t/n),s=i/(2*Math.sqrt(t*n)),g=s<1?u*Math.sqrt(1-s*s):0,p=s<1?(s*u+-r)/g:-r+u;let o=a?a*e/1e3:e;return s<1?o=Math.exp(-o*s*u)*(Math.cos(g*o)+p*Math.sin(g*o)):o=(1+p*o)*Math.exp(-o*u),1-o},l=new Map,h=1e5;function N([e,n,t,i]=[]){let r=[e,n,t,i],a=`${r}`;if(l.has(a))return l.get(a);const u=1/6;let s=0,g=0;for(;++g<h;){if(Math.abs(1-c(s,r))<.001){let o=s,b=1;for(;++g<h&&(s+=u,!(Math.abs(1-c(s,r))>=.001));)if(b++,b===16){const O=o*1e3;return l.set(a,[O,g]),[O,g]}}s+=u}const p=s*1e3;return l.set(a,[p,g]),[p,g]}function w(e){return(n,t=[],i)=>1-e(1-n,t,i)}function k(e){return function(n,t=[],i){return n<.5?e(n*2,t,i)/2:1-e(n*-2+2,t,i)/2}}function P(e){return function(n,t=[],i){return n<.5?(1-e(1-n*2,t,i))/2:(e(n*2-1,t,i)+1)/2}}const x=c,L=w(c),T=k(c),j=P(c);function E(e,n,t=3){const i=n.length-1,r=m(Math.floor(e*i),0,i-1),a=n[r],u=n[r+1],s=(e-r/i)*i;return I(d(s,a,u),t)}function S(e,n){const t=n.length-1;e=m(e,0,1);const i=Math.round(e*t);return n[i]}const U=S;function A(e,n,t=3){let i="";return F(n[0])&&(i=M(n[0])),E(e,n.map(r=>typeof r=="number"?r:parseFloat(r)),t)+i}function C(e,n,t=3){return n.every(a=>typeof a=="number")?E(e,n,t):n.every(a=>F(a))?A(e,n,t):S(e,n)}exports.EasingFunctions={spring:c,"spring-in":x,"spring-out":L,"spring-in-out":T,"spring-out-in":j};exports.EasingFunctionKeys=Object.keys(exports.EasingFunctions);function K(e,n){exports.EasingFunctions={...exports.EasingFunctions,[e]:n},exports.EasingFunctionKeys=Object.keys(exports.EasingFunctions)}function G(e){exports.EasingFunctions={...exports.EasingFunctions,...e},exports.EasingFunctionKeys=Object.keys(exports.EasingFunctions)}function q(e){const n=/(\(|\s)([^)]+)\)?/.exec(e.toString());return n?n[2].split(",").map(t=>{let i=parseFloat(t);return Number.isNaN(i)?t.trim():i}):[]}function y(e={}){const n=typeof e=="string"||Array.isArray(e)&&typeof e[0]=="function";let{easing:t=[c,1,100,10,0],numPoints:i=38,decimal:r=3}=n?{easing:e}:e;if(typeof t=="string"){const a=exports.EasingFunctions[t.replace(/(\(|\s).+/,"").toLowerCase().trim()],u=q(t);t=[a,...u]}return{easing:t,numPoints:i,decimal:r}}const f=new Map;function _(e={}){let{easing:n,numPoints:t}=y(e);if(Array.isArray(n)){if(typeof n[0]!="function")throw new Error("[spring-easing] A frame function is required as the first element in the easing array, e.g. [SpringFrame, ...]");n.length>1&&n.length<5&&console.warn(`[spring-easing] Be careful of only setting some of the spring parameters, you've only set ${5-n.length} spring parameter(s). The easing works best in the format: 
* "spring-out(mass, stiffness, damping, velocity)" or 
* [SpringOutFrame, mass, stiffness, damping, velocity].`),n.length>5&&console.warn(`[spring-easing] You entered ${5-n.length} more spring parameter(s) than necessary. The easing needs to be in the format: 
* "spring-out(mass, stiffness, damping, velocity)" or 
* [SpringOutFrame, mass, stiffness, damping, velocity].`)}else throw new Error(`[spring-easing] The easing needs to be in the format:  
* "spring-out(mass, stiffness, damping, velocity)" or 
* [SpringOutFrame, mass, stiffness, damping, velocity], the easing recieved is "${n}", [spring-easing] doesn't really know what to do with that.`);let[i,...r]=n;const[a,u=38]=N(r);t||(t=u);const s=`${r},${t}`;if(f.has(s)){let o=f.get(s);if(o.has(i))return o.get(i)}const g=[];for(let o=0;o<t;o++)g[o]=i(o/(t-1),r,a);const p=f.has(s)?f.get(s):new WeakMap;return p.set(i,[g,a]),f.set(s,p),[g,a]}function $(e,n={},t=C){const i=y(n),[r,a]=_(i);return[r.map(u=>t(u,e,i.decimal)),a]}exports.EaseInOut=k;exports.EaseOut=w;exports.EaseOutIn=P;exports.EasingDurationCache=l;exports.EasingOptions=y;exports.FramePtsCache=f;exports.GenerateSpringFrames=_;exports.INFINITE_LOOP_LIMIT=h;exports.SpringEasing=$;exports.SpringFrame=c;exports.SpringInFrame=x;exports.SpringInOutFrame=T;exports.SpringOutFrame=L;exports.SpringOutInFrame=j;exports.default=$;exports.getSpringDuration=N;exports.getUnit=M;exports.interpolateComplex=C;exports.interpolateNumber=E;exports.interpolateSequence=S;exports.interpolateString=A;exports.interpolateUsingIndex=U;exports.isNumberLike=F;exports.limit=m;exports.parseEasingParameters=q;exports.registerEasingFunction=K;exports.registerEasingFunctions=G;exports.scale=d;exports.toAnimationFrames=D;exports.toFixed=I;
